// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package marina

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarinaClient is the client API for Marina service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarinaClient interface {
	CatalogItemGet(ctx context.Context, in *CatalogItemGetArg, opts ...grpc.CallOption) (*CatalogItemGetRet, error)
}

type marinaClient struct {
	cc grpc.ClientConnInterface
}

func NewMarinaClient(cc grpc.ClientConnInterface) MarinaClient {
	return &marinaClient{cc}
}

func (c *marinaClient) CatalogItemGet(ctx context.Context, in *CatalogItemGetArg, opts ...grpc.CallOption) (*CatalogItemGetRet, error) {
	out := new(CatalogItemGetRet)
	err := c.cc.Invoke(ctx, "/protos.marina.Marina/CatalogItemGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarinaServer is the server API for Marina service.
// All implementations must embed UnimplementedMarinaServer
// for forward compatibility
type MarinaServer interface {
	CatalogItemGet(context.Context, *CatalogItemGetArg) (*CatalogItemGetRet, error)
	mustEmbedUnimplementedMarinaServer()
}

// UnimplementedMarinaServer must be embedded to have forward compatible implementations.
type UnimplementedMarinaServer struct {
}

func (UnimplementedMarinaServer) CatalogItemGet(context.Context, *CatalogItemGetArg) (*CatalogItemGetRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CatalogItemGet not implemented")
}
func (UnimplementedMarinaServer) mustEmbedUnimplementedMarinaServer() {}

// UnsafeMarinaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarinaServer will
// result in compilation errors.
type UnsafeMarinaServer interface {
	mustEmbedUnimplementedMarinaServer()
}

func RegisterMarinaServer(s grpc.ServiceRegistrar, srv MarinaServer) {
	s.RegisterService(&Marina_ServiceDesc, srv)
}

func _Marina_CatalogItemGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogItemGetArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarinaServer).CatalogItemGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.marina.Marina/CatalogItemGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarinaServer).CatalogItemGet(ctx, req.(*CatalogItemGetArg))
	}
	return interceptor(ctx, in, info, handler)
}

// Marina_ServiceDesc is the grpc.ServiceDesc for Marina service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marina_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.marina.Marina",
	HandlerType: (*MarinaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CatalogItemGet",
			Handler:    _Marina_CatalogItemGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/marina/marina_interface.proto",
}
