{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "marina.serviceAccountName" . }}
  labels:
    {{- include "marina.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
   {{- with .Values.serviceAccount.annotations }}
   {{- toYaml . | nindent 4 }}
   {{- end }}
{{- end }}
